channels:
  - name: "Первый канал"
    url: "smotret.tv"
    referer: "smotret.tv"

  - name: "Россия 1"
    url: "smotret.tvtv/public/784-rossija-1.html"
    referer: "smotret.tv"

  - name: "Звезда"
    url: "smotret.tvtv/public/310-zvezda.html"
    referer: "smotret.tv"

  - name: "ТНТ"
    url: "smotret.tvtv/entertainment/329-tnt.html"
    referer: "smotret.tv"

  - name: "СТС"
    url: "smotret.tvtv/entertainment/783-sts.html"
    referer: "smotret.tv"

  - name: "Россия 24"
    url: "smotret.tvtv/news/217-rossija-24.html"
    referer: "smotret.tv" 0
          git push
          git commit -m "Update tokens" || exit 0
          git push
